server:
  port: 8081

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://postgres:5432/userdb
    username: postgres
    password: 1
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
    enabled: true
  instance:
    prefer-ip-address: true

# ВРЕМЕННО ОТКЛЮЧАЕМ CIRCUIT BREAKER
resilience4j:
  circuitbreaker:
    enabled: false
  retry:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
