# Kafka Configuration
spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: userEvent:com.example.userservice.event.UserCreatedEvent
        spring.json.add.type.headers: false

app:
  kafka:
    topic:
      user-events: user-events
